version: "3.8"

services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs --allowInjection
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters


  postgres:
      container_name: my_postgres
      volumes:
      - ./postgres_database.sql:/docker-entrypoint-initdb.d/postgres_database.sql
      image: postgres
      ports:
      - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: mac@dev
        POSTGRES_DB: payment_gateway


